language: python
python:
  - 2.7
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install --upgrade pip
  - pip install cython pytest pytest-cov coveralls
install:
  - pip install --no-cache-dir -U -r requirements.txt | cat
script:
  - pytest -v --cov=fdm --cov-report term-missing
after_success:
  - coveralls
